### ISSUE TITLE
Please Upload this somewhere where github can see it?

### ISSUE THREAD

**Issue by Skyladd** [TheKillerTacos/SkyBlockPVP#6]
https://drive.google.com/file/d/0B9EFuluan--kbk9RbXcwaGFrblU/view?usp=sharing

I edited the image for the plugin :D

**Comment by TheKillerTacos** [comment]
OK

**Comment by Skyladd** [comment]
I tried but the image wouldnt show. Hopefully you know how lol

**Comment by Skyladd** [comment]
Fixed

**Comment by TheKillerTacos** [comment]
ok
